/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ittapiros;

/**
 *
 * @author Drégely Imre
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPohar1 = new javax.swing.JButton();
        btnPohar2 = new javax.swing.JButton();
        btnPohar3 = new javax.swing.JButton();
        lbVisszajelzes = new javax.swing.JLabel();
        cbGolyoValtoztatas = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFajl = new javax.swing.JMenu();
        mnMentes = new javax.swing.JMenuItem();
        mnBetolt = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnUjJatek = new javax.swing.JMenu();
        rbm3Pohar = new javax.swing.JRadioButtonMenuItem();
        rbm4Pohar = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Itt a piros");

        btnPohar1.setText("Pohár 1");

        btnPohar2.setText("Pohár 2");

        btnPohar3.setText("Pohár 3");
        btnPohar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPohar3ActionPerformed(evt);
            }
        });

        lbVisszajelzes.setText("Találat");

        cbGolyoValtoztatas.setText("Tipp után golyó helyzetének változtatása");

        mnFajl.setText("Fájl");

        mnMentes.setText("Mentés");
        mnFajl.add(mnMentes);

        mnBetolt.setText("Betöltés");
        mnFajl.add(mnBetolt);

        jMenuBar1.add(mnFajl);

        jMenu2.setText("Játék");

        mnUjJatek.setText("Új játék");

        rbm3Pohar.setSelected(true);
        rbm3Pohar.setText("3 pohár");
        mnUjJatek.add(rbm3Pohar);

        rbm4Pohar.setSelected(true);
        rbm4Pohar.setText("4 pohár");
        mnUjJatek.add(rbm4Pohar);

        jMenu2.add(mnUjJatek);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(lbVisszajelzes)
                        .addGap(190, 190, 190))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPohar1)
                        .addGap(77, 77, 77)
                        .addComponent(btnPohar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPohar3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbGolyoValtoztatas)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPohar1)
                    .addComponent(btnPohar2)
                    .addComponent(btnPohar3))
                .addGap(40, 40, 40)
                .addComponent(lbVisszajelzes)
                .addGap(18, 18, 18)
                .addComponent(cbGolyoValtoztatas)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPohar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPohar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPohar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPohar1;
    private javax.swing.JButton btnPohar2;
    private javax.swing.JButton btnPohar3;
    private javax.swing.JCheckBox cbGolyoValtoztatas;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbVisszajelzes;
    private javax.swing.JMenuItem mnBetolt;
    private javax.swing.JMenu mnFajl;
    private javax.swing.JMenuItem mnMentes;
    private javax.swing.JMenu mnUjJatek;
    private javax.swing.JRadioButtonMenuItem rbm3Pohar;
    private javax.swing.JRadioButtonMenuItem rbm4Pohar;
    // End of variables declaration//GEN-END:variables
}
